[package]
name = "rktpb"
version = "1.0.0"
authors = ["Sergio Benitez <sb@sergio.bz>"]
edition = "2024"
description = "A pastebin that does just enough to be really useful."
repository = "https://github.com/SergioBenitez/rktpb"
readme = "README.md"
keywords = ["pastebin", "rocket", "server", "markdown", "highlight"]
license = "AGPL-3.0-only"
categories = ["web-programming::http-server"]

[lints.clippy]
large_enum_variant = "allow"
mutable_key_type = "allow"

[dependencies]
rocket = { version = "0.5", default-features = false }
rocket_dyn_templates = { version = "0.2", default-features = false, features = ["minijinja"] }
rand = { version = "0.10", default-features = false, features = ["thread_rng"] }
syntect = { version = "5", default-features = false, features = ["html", "default-syntaxes", "regex-onig", "plist-load"] }
comrak = { version = "0.50", default-features = false }
humantime = "2.1"
humantime-serde = "1.1"
thiserror = "*"
